services:
  - type: web
    name: project-sarah
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y php php-cli php-curl php-mbstring php-xml
      npm install
    startCommand: node index.js
    autoDeploy: true